name = "form-tool-worker"
main = "./tools/form-tool/formtool-v2.js"
compatibility_date = "2023-10-30"

# Trigger builds with each deployment
[build]
command = "npm run build"

# Define production-specific configurations
[env.production]
# Add your domain routes if needed
# routes = [
#   { pattern = "yourdomain.com/form-tool/*", zone_name = "yourdomain.com" }
# ]

# Define any environment variables your worker needs
# [vars]
# MY_VARIABLE = "value"

# Customize worker settings if needed
# [site]
# bucket = "./tools"